### ISSUE TITLE
Remove consul agent

### ISSUE THREAD

**Issue by sberryman** [autopilotpattern/influxdb#2]
Any reason you removed the consul agent coprocess? It seems like that is the way to go and what all the other example autopilotpattern projects are doing...

commit: e03775d618e3a49530662c34b48b237aaa1136b2

**Comment by geek** [comment]
@sberryman no reason, and I will add it in.

**Comment by sberryman** [comment]
I can add it back and upgrade influx to 1.2.2-alipine in the process if you want. I need to work on this today anyways. 

I'll also bump containerpilot to 2.7.2 if you don't mind.

**Comment by sberryman** [comment]
I guess I should ask, do you want consul agent to be optional using `CONSUL_AGENT=1` or make it required? The mongodb pattern has it required but most of the other projects are optional. I'm not really sure why you would ever want it to be optional though...
